### ISSUE TITLE
URIParser.escape not escaping newlines correctly?

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/URIParser.jl#27]
Is it just me or this technically correct?
```julia
julia> str = "hey there newline: \n"
"hey there newline: \n"

julia> URIParser.escape(str)
"hey%20there%20newline%3A%20%A"
```
whereas [this service](http://meyerweb.com/eric/tools/dencoder/) correctly gives
```
hey%20there%20newline%3A%20%0A
```
I have an API I'm trying to hit, but it's rejecting because the newlines aren't escaped properly

**Comment by malmaud** [comment]
You're right - `%A` is not a valid escape sequence.

**Comment by quinnj** [comment]
Looks like the culprit is [here](https://github.com/JuliaWeb/URIParser.jl/blob/54a8dd106ee6e261bf9beed5affdbecf593a6cd8/src/esc.jl#L29). Which correctly returns the hex value for '\n' as 'A', but isn't doing any kind of padding because it's a single "digit"

**Comment by quinnj** [comment]
Thanks!

**Comment by quinnj** [comment]
I'm kind of baffled how this wasn't caught before....

**Comment by malmaud** [comment]
When I first started working on the webstack, HttpServer was only allowed
to set a single cooke in its response. So nothing surprises me anymore.

**Comment by Keno** [comment]
Is the added dependency on Lazy really necessary here? I would prefer this package to stay stand-alone.

**Comment by malmaud** [comment]
It's not necessary.

**Comment by malmaud** [comment]
I just like the threading macros. But if there's some kind of technical or stylistic issue with depending on it,  it's easily removed.

**Comment by Keno** [comment]
This package is one of the few roots of our package ecosystem because BinDeps depends on it. I would prefer it to not depend on any other packages.

**Comment by malmaud** [comment]
Done.

**Comment by Keno** [comment]
Thanks!

**Comment by malmaud** [comment]
np

**Comment by samoconnor** [comment]
Hi @malmaud,
Any chance of making a release with this fix?
I'm planning to make a release of my AWS / Lambda library soon, but that code depends on this fix. https://github.com/samoconnor/OCAWS.jl

**Comment by malmaud** [comment]
Sure

**Comment by malmaud** [comment]
Done
