### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/URIParser.jl#33]
Hi,

Any ideas why build is failing? Any hints as to how to fix it? I could have a go at a PR with some guidance.

Best regards,
Eric

Edit: Looks like an error on Linux (iOS is passing) during the build step. I'm on Windows and unlikely to be able to help fix this one.

https://travis-ci.org/JuliaWeb/URIParser.jl/jobs/115475359#L125

**Comment by malmaud** [comment]
I think this isn't happening anymore, but let me know if it still is.
