### ISSUE TITLE
Deprecation warnings re utf8(), bytestring() and writemime()

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/URIParser.jl#42]
esc.jl uses deprecated `utf8` and `bytestring`.

`parser.jl` defines a method for non-existant `Base.writemime`

**Comment by randyzwitch** [comment]
I should be able to tackle this in the next week or so (hopefully earlier)

**Comment by samoconnor** [comment]
@randyzwitch Note, there is a patch in #41 with an incomplete attempt at fixing this.

**Comment by yuyichao** [comment]
This has already been fixed. There one left over use of `writemime` in the test and it's fixed in https://github.com/JuliaWeb/URIParser.jl/pull/44
