### ISSUE TITLE
Relative URL parsing

### ISSUE THREAD

**Issue by c42f** [JuliaWeb/URIParser.jl#71]
Should this package recognize "relative URLs" as described in https://www.ietf.org/rfc/rfc1808.txt?

Python's urllib.parse seems to do this — see https://docs.python.org/3/library/urllib.parse.html

**Comment by quinnj** [comment]
This repo hasn't been actively maintained for a while and should be archived; best off to file an issue at HTTP.jl where we have the URIs.jl module that has a bunch of update from this original code.

**Comment by c42f** [comment]
Excellent, it seems `HTTP.URIs` can already parse relative URIs.

Ideally I'd not have to depend on all of HTTP.jl just for some light URI parsing but for now it seems fine.

**Comment by quinnj** [comment]
There are plans to register URIs.jl module as its own package; I just haven't gotten around to it yet

**Comment by c42f** [comment]
Ah now I understand. I thought there were plans for this (based on some slack discussion a while back?) and I figured `URIParser` was the resulting package.

**Comment by c42f** [comment]
@quinnj I went ahead and extracted the URI parsing functionality from HTTP.jl, preserving the git history and fixing up various things to make sure the tests pass. Further cleanup could be done but for now I think this works ok.

https://github.com/c42f/URIs.jl

Would you like to move this to JuliaWeb?

**Comment by quinnj** [comment]
Yeah, that sounds good to me. I had wanted to try out actually leaving the code inside the HTTP.jl repo (as a subdirectory package) and registering it from there, but figuring out exactly how to do that has been the main blocker in doing it 😄 . The URIs.jl code is separate enough that I'm fine with it living as its own repo, but if you're up for just plopping that code into the HTTP.jl directory as a PR, I'd love to see if we can make that work.

**Comment by c42f** [comment]
Heh, I don't know how to do this either.

I found https://github.com/JuliaLang/Pkg.jl/issues/1251#issuecomment-621632170 which contains some links to where the subdirs stuff was implemented.

Also as one working example, it seems SnoopCompile did this: https://github.com/timholy/SnoopCompile.jl/tree/master/SnoopCompileCore

Note that as a minor downside, if we put URLs as a subdir of HTTP and don't place HTTP in a subdir as well, HTTP will include the URLs source code as part of the package (even though it won't be used). cf. https://github.com/JuliaLang/Pkg.jl/issues/1251#issuecomment-641081380

**Comment by c42f** [comment]
Hmm. Reading through some of those issues it seems like using a subdir might be a fair amount of messing around without a lot of benefit at this point (https://github.com/JuliaLang/Pkg.jl/issues/1251#issuecomment-647173791).

Also there's CI to consider — do you want CI to be done separately or together?

Overall I get the vibe that it just might not be worth it at this point.

**Comment by quinnj** [comment]
Thanks for digging in; let's just move the URIs.jl repo to JuliaWeb (I invited you as a member, so you should be able to do it) and have it live as a separate package.

**Comment by c42f** [comment]
Oop done!

I had a little mishap with permissions (I forgot to accept your JuliaWeb invite before transferring) so you'll get some spam, sorry!
